/*
 * This code and all components © 2015 - 2019 Wowza Media Systems, LLC. All rights reserved.
 * This code is licensed pursuant to the BSD 3-Clause License.
 * 
 * Wowza Streaming Cloud REST API Reference Documentation
 *
 * OpenAPI spec version: v1.3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.wowza.cloudsdk.client.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.List;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.time.OffsetDateTime;

/**
 * Limits
 */
@javax.annotation.Generated(value ="com.wowza.cloudsdk.JavaCreate", date = "2019-03-02T10:45:24.077Z")
public class Limits {
  @SerializedName("fields")
  private List<String> fields = null;

  @SerializedName("from")
  private OffsetDateTime from = null;

  @SerializedName("to")
  private OffsetDateTime to = null;

  public Limits fields(List<String> fields) {
    this.fields = fields;
    return this;
  }

   /**
   * A comma-separated list of fields that were returned in the request.
   * @return fields
  **/
  @ApiModelProperty(required = true, value = "A comma-separated list of fields that were returned in the request.")
  public List<String> getFields() {
    return fields;
  }

  public void setFields(List<String> fields) {
    this.fields = fields;
  }

  public Limits from(OffsetDateTime from) {
    this.from = from;
    return this;
  }

   /**
   * The start of range of time when the metrics were aggregated for the query.
   * @return from
  **/
  @ApiModelProperty(required = true, value = "The start of range of time when the metrics were aggregated for the query.")
  public OffsetDateTime getFrom() {
    return from;
  }

  public void setFrom(OffsetDateTime from) {
    this.from = from;
  }

  public Limits to(OffsetDateTime to) {
    this.to = to;
    return this;
  }

   /**
   * The end of the range of time when the metrics were aggregated for the query.
   * @return to
  **/
  @ApiModelProperty(required = true, value = "The end of the range of time when the metrics were aggregated for the query.")
  public OffsetDateTime getTo() {
    return to;
  }

  public void setTo(OffsetDateTime to) {
    this.to = to;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Limits limits1 = (Limits) o;
    return Objects.equals(this.fields, limits1.fields) &&
        Objects.equals(this.from, limits1.from) &&
        Objects.equals(this.to, limits1.to);
  }

  @Override
  public int hashCode() {
    return Objects.hash(fields, from, to);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Limits {\n");
    
    sb.append("    fields: ").append(toIndentedString(fields)).append("\n");
    sb.append("    from: ").append(toIndentedString(from)).append("\n");
    sb.append("    to: ").append(toIndentedString(to)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

