/*
 * This code and all components © 2015 - 2019 Wowza Media Systems, LLC. All rights reserved.
 * This code is licensed pursuant to the BSD 3-Clause License.
 * 
 * Wowza Streaming Cloud REST API Reference Documentation
 *
 * OpenAPI spec version: v1.3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.wowza.cloudsdk.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * PlaybackUrl
 */
public class PlaybackUrl {
  @SerializedName("name")
  private String name = null;

  @SerializedName("output_id")
  private String outputId = null;

  @SerializedName("url")
  private String url = null;

  public PlaybackUrl name(String name) {
    this.name = name;
    return this;
  }

   /**
   * The name of the playback URL: &lt;strong&gt;source&lt;/strong&gt;, &lt;strong&gt;default&lt;/strong&gt;, &lt;strong&gt;passthrough&lt;/strong&gt;, or the output rendition&#39;s resolution.
   * @return name
  **/
  @ApiModelProperty(example = "hls", value = "The name of the playback URL: <strong>source</strong>, <strong>default</strong>, <strong>passthrough</strong>, or the output rendition's resolution.")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public PlaybackUrl outputId(String outputId) {
    this.outputId = outputId;
    return this;
  }

   /**
   * Only for output rendition-based playback URLs, not source playback URLs. The unique alphanumeric string that identifies the output rendition.
   * @return outputId
  **/
  @ApiModelProperty(example = "dcxq5q6c", value = "Only for output rendition-based playback URLs, not source playback URLs. The unique alphanumeric string that identifies the output rendition.")
  public String getOutputId() {
    return outputId;
  }

  public void setOutputId(String outputId) {
    this.outputId = outputId;
  }

  public PlaybackUrl url(String url) {
    this.url = url;
    return this;
  }

   /**
   * The playback URL for the source or output rendition.
   * @return url
  **/
  @ApiModelProperty(example = "https://abcdef.dev.entrypoint.cloud.wowza.com/app-16ea/ngrp:43a23e5a_all/playlist.m3u8", value = "The playback URL for the source or output rendition.")
  public String getUrl() {
    return url;
  }

  public void setUrl(String url) {
    this.url = url;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PlaybackUrl playbackUrl = (PlaybackUrl) o;
    return Objects.equals(this.name, playbackUrl.name) &&
        Objects.equals(this.outputId, playbackUrl.outputId) &&
        Objects.equals(this.url, playbackUrl.url);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, outputId, url);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PlaybackUrl {\n");
    
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    outputId: ").append(toIndentedString(outputId)).append("\n");
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

