/*
 * This code and all components © 2015 - 2019 Wowza Media Systems, LLC. All rights reserved.
 * This code is licensed pursuant to the BSD 3-Clause License.
 * 
 * Wowza Streaming Cloud REST API Reference Documentation
 *
 * OpenAPI spec version: v1.3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.wowza.cloudsdk.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.wowza.cloudsdk.client.model.IndexStreamSource;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * 
 */
@ApiModel(description = "")
public class StreamSources {
  @SerializedName("stream_sources")
  private List<IndexStreamSource> streamSources = new ArrayList<IndexStreamSource>();

  public StreamSources streamSources(List<IndexStreamSource> streamSources) {
    this.streamSources = streamSources;
    return this;
  }

  public StreamSources addStreamSourcesItem(IndexStreamSource streamSourcesItem) {
    this.streamSources.add(streamSourcesItem);
    return this;
  }

   /**
   * Get streamSources
   * @return streamSources
  **/
  @ApiModelProperty(required = true, value = "")
  public List<IndexStreamSource> getStreamSources() {
    return streamSources;
  }

  public void setStreamSources(List<IndexStreamSource> streamSources) {
    this.streamSources = streamSources;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    StreamSources streamSources = (StreamSources) o;
    return Objects.equals(this.streamSources, streamSources.streamSources);
  }

  @Override
  public int hashCode() {
    return Objects.hash(streamSources);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class StreamSources {\n");
    
    sb.append("    streamSources: ").append(toIndentedString(streamSources)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

