/*
 * This code and all components © 2015 - 2019 Wowza Media Systems, LLC. All rights reserved.
 * This code is licensed pursuant to the BSD 3-Clause License.
 * 
 * Wowza Streaming Cloud REST API Reference Documentation
 *
 * OpenAPI spec version: v1.3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.wowza.cloudsdk.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.wowza.cloudsdk.client.model.TranscoderState;
import java.io.IOException;

/**
 * TranscoderCreateState
 */
public class TranscoderCreateState {
  @SerializedName("transcoder")
  private TranscoderState transcoder = null;

  public TranscoderCreateState transcoder(TranscoderState transcoder) {
    this.transcoder = transcoder;
    return this;
  }

   /**
   * Get transcoder
   * @return transcoder
  **/
  @ApiModelProperty(required = true, value = "")
  public TranscoderState getTranscoderState() {
    return transcoder;
  }

  public void setTranscoderState(TranscoderState transcoder) {
    this.transcoder = transcoder;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TranscoderCreateState inlineResponse20040 = (TranscoderCreateState) o;
    return Objects.equals(this.transcoder, inlineResponse20040.transcoder);
  }

  @Override
  public int hashCode() {
    return Objects.hash(transcoder);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TranscoderCreateState {\n");
    
    sb.append("    transcoder: ").append(toIndentedString(transcoder)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

