/*
 * This code and all components © 2015 - 2019 Wowza Media Systems, LLC. All rights reserved.
 * This code is licensed pursuant to the BSD 3-Clause License.
 * 
 * Wowza Streaming Cloud REST API Reference Documentation
 *
 * OpenAPI spec version: v1.3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.wowza.cloudsdk.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.time.OffsetDateTime;

/**
 * 
 */
@ApiModel(description = "")
public class Uptime {
  @SerializedName("billed")
  private Boolean billed = null;

  @SerializedName("created_at")
  private OffsetDateTime createdAt = null;

  @SerializedName("ended_at")
  private OffsetDateTime endedAt = null;

  @SerializedName("id")
  private String id = null;

  @SerializedName("running")
  private Boolean running = null;

  @SerializedName("started_at")
  private OffsetDateTime startedAt = null;

  @SerializedName("transcoder_id")
  private String transcoderId = null;

  @SerializedName("updated_at")
  private String updatedAt = null;

  public Uptime billed(Boolean billed) {
    this.billed = billed;
    return this;
  }

   /**
   * A Boolean value that indicates if the usage generated by this uptime has been sent for billing processing.
   * @return billed
  **/
  @ApiModelProperty(value = "A Boolean value that indicates if the usage generated by this uptime has been sent for billing processing.")
  public Boolean isBilled() {
    return billed;
  }

  public void setBilled(Boolean billed) {
    this.billed = billed;
  }

  public Uptime createdAt(OffsetDateTime createdAt) {
    this.createdAt = createdAt;
    return this;
  }

   /**
   * The date and time that the uptime record was created.
   * @return createdAt
  **/
  @ApiModelProperty(example = "", value = "The date and time that the uptime record was created.")
  public OffsetDateTime getCreatedAt() {
    return createdAt;
  }

  public void setCreatedAt(OffsetDateTime createdAt) {
    this.createdAt = createdAt;
  }

  public Uptime endedAt(OffsetDateTime endedAt) {
    this.endedAt = endedAt;
    return this;
  }

   /**
   * The date and time that the transcoder was stopped for this uptime. If this value is not present, it indicates that the transcoder is currently running.
   * @return endedAt
  **/
  @ApiModelProperty(example = "", value = "The date and time that the transcoder was stopped for this uptime. If this value is not present, it indicates that the transcoder is currently running.")
  public OffsetDateTime getEndedAt() {
    return endedAt;
  }

  public void setEndedAt(OffsetDateTime endedAt) {
    this.endedAt = endedAt;
  }

  public Uptime id(String id) {
    this.id = id;
    return this;
  }

   /**
   * The unique alphanumeric string that identifies the uptime record.
   * @return id
  **/
  @ApiModelProperty(example = "", value = "The unique alphanumeric string that identifies the uptime record.")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public Uptime running(Boolean running) {
    this.running = running;
    return this;
  }

   /**
   * A Boolean value that indicates if the transcoder is still running for this uptime.
   * @return running
  **/
  @ApiModelProperty(value = "A Boolean value that indicates if the transcoder is still running for this uptime.")
  public Boolean isRunning() {
    return running;
  }

  public void setRunning(Boolean running) {
    this.running = running;
  }

  public Uptime startedAt(OffsetDateTime startedAt) {
    this.startedAt = startedAt;
    return this;
  }

   /**
   * The date and time that the transcoder started for this uptime.
   * @return startedAt
  **/
  @ApiModelProperty(example = "", value = "The date and time that the transcoder started for this uptime.")
  public OffsetDateTime getStartedAt() {
    return startedAt;
  }

  public void setStartedAt(OffsetDateTime startedAt) {
    this.startedAt = startedAt;
  }

  public Uptime transcoderId(String transcoderId) {
    this.transcoderId = transcoderId;
    return this;
  }

   /**
   * The unique alphanumeric string that identifies the transcoder.
   * @return transcoderId
  **/
  @ApiModelProperty(example = "", value = "The unique alphanumeric string that identifies the transcoder.")
  public String getTranscoderId() {
    return transcoderId;
  }

  public void setTranscoderId(String transcoderId) {
    this.transcoderId = transcoderId;
  }

  public Uptime updatedAt(String updatedAt) {
    this.updatedAt = updatedAt;
    return this;
  }

   /**
   * The date and time that the uptime record was updated.
   * @return updatedAt
  **/
  @ApiModelProperty(example = "", value = "The date and time that the uptime record was updated.")
  public String getUpdatedAt() {
    return updatedAt;
  }

  public void setUpdatedAt(String updatedAt) {
    this.updatedAt = updatedAt;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Uptime uptime = (Uptime) o;
    return Objects.equals(this.billed, uptime.billed) &&
        Objects.equals(this.createdAt, uptime.createdAt) &&
        Objects.equals(this.endedAt, uptime.endedAt) &&
        Objects.equals(this.id, uptime.id) &&
        Objects.equals(this.running, uptime.running) &&
        Objects.equals(this.startedAt, uptime.startedAt) &&
        Objects.equals(this.transcoderId, uptime.transcoderId) &&
        Objects.equals(this.updatedAt, uptime.updatedAt);
  }

  @Override
  public int hashCode() {
    return Objects.hash(billed, createdAt, endedAt, id, running, startedAt, transcoderId, updatedAt);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Uptime {\n");
    
    sb.append("    billed: ").append(toIndentedString(billed)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    endedAt: ").append(toIndentedString(endedAt)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    running: ").append(toIndentedString(running)).append("\n");
    sb.append("    startedAt: ").append(toIndentedString(startedAt)).append("\n");
    sb.append("    transcoderId: ").append(toIndentedString(transcoderId)).append("\n");
    sb.append("    updatedAt: ").append(toIndentedString(updatedAt)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

