/*
 * This code and all components © 2015 - 2019 Wowza Media Systems, LLC. All rights reserved.
 * This code is licensed pursuant to the BSD 3-Clause License.
 * 
 * Wowza Streaming Cloud REST API Reference Documentation
 *
 * OpenAPI spec version: v1.3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.wowza.cloudsdk.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.wowza.cloudsdk.client.model.HashOfTotals;
import com.wowza.cloudsdk.client.model.UsageNetworkStreamTarget;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * 
 */
@ApiModel(description = "")
public class UsageNetworkStreamTargets {
  @SerializedName("total")
  private HashOfTotals total = null;

  @SerializedName("stream_targets")
  private List<UsageNetworkStreamTarget> streamTargets = null;

  public UsageNetworkStreamTargets total(HashOfTotals total) {
    this.total = total;
    return this;
  }

   /**
   * Get total
   * @return total
  **/
  @ApiModelProperty(value = "")
  public HashOfTotals getTotal() {
    return total;
  }

  public void setTotal(HashOfTotals total) {
    this.total = total;
  }

  public UsageNetworkStreamTargets streamTargets(List<UsageNetworkStreamTarget> streamTargets) {
    this.streamTargets = streamTargets;
    return this;
  }

  public UsageNetworkStreamTargets addStreamTargetsItem(UsageNetworkStreamTarget streamTargetsItem) {
    if (this.streamTargets == null) {
      this.streamTargets = new ArrayList<UsageNetworkStreamTarget>();
    }
    this.streamTargets.add(streamTargetsItem);
    return this;
  }

   /**
   * Get streamTargets
   * @return streamTargets
  **/
  @ApiModelProperty(value = "")
  public List<UsageNetworkStreamTarget> getStreamTargets() {
    return streamTargets;
  }

  public void setStreamTargets(List<UsageNetworkStreamTarget> streamTargets) {
    this.streamTargets = streamTargets;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UsageNetworkStreamTargets usageNetworkStreamTargets = (UsageNetworkStreamTargets) o;
    return Objects.equals(this.total, usageNetworkStreamTargets.total) &&
        Objects.equals(this.streamTargets, usageNetworkStreamTargets.streamTargets);
  }

  @Override
  public int hashCode() {
    return Objects.hash(total, streamTargets);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UsageNetworkStreamTargets {\n");
    
    sb.append("    total: ").append(toIndentedString(total)).append("\n");
    sb.append("    streamTargets: ").append(toIndentedString(streamTargets)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

